name: Build

env:
  QUAY_BASE: quay.io/miabbott/

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build container image"
    strategy:
      matrix:
        ctrname: ["bpytop"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push container images
        env:
          CTRNAME: ${{ matrix.ctrname }}
        run: |
          set -xeuo pipefail
          mkdir -p ~/.docker
          cat > ~/.docker/config.json <<EOF
          ${{ secrets.QUAY_AUTH }}
          EOF
          podman build -f dockerfiles/$CNTRNAME/Dockerfile -t "${{ env.QUAY_BASE }}/$CTRNAME:latest" .
          podman push ""${{ env.QUAY_BASE }}/$CTRNAME:latest""
          rm ~/.docker/config.json

